// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DowntimeCollection_Demo {
	
	
	public partial class CnmPager {
		
		protected System.Web.UI.WebControls.Literal Literal1;
		
		protected System.Web.UI.WebControls.Literal PageIndexLiteral;
		
		protected System.Web.UI.WebControls.Literal PageCountLiteral;
		
		protected System.Web.UI.WebControls.HyperLink First;
		
		protected System.Web.UI.WebControls.HyperLink Prev;
		
		protected System.Web.UI.WebControls.HyperLink Next;
		
		protected System.Web.UI.WebControls.HyperLink Last;
	}
}
